- config/database.php
Currently it's not possible to set the database prefix without overriding the config file in the application, it seems like allowing it to be set at the environment level out of the box would be a clean addition, as it's a fairly common requirement.
Apologies, the previous version of this pull request was made against the master accidentally.
> Support configuration of database prefix in .env

- src/Application.php
- tests/FullApplicationTest.php
According to phpdoc for ``Illuminate\Contracts\Foundation\Application::register()`` and ``Laravel\Lumen\Application::register()`` it must be possible to pass instance of ``Illuminate\Support\ServiceProvider`` as first parameter. This pull request makes it really an option.
> Application::register() $provider parameter

- src/Application.php
Second try at fixing errors when using the built-in PHP server + `server.php` router file with Lumen.
> Support built-in PHP server

- src/Application.php
Currently, when using any of the `Log` facade methods we will get a fatal error:
```Fatal error: Call to undefined method Illuminate\Support\Facades\Log::error() in vendor/illuminate/support/Facades/Facade.php on line 210```
This is due to the Laravel `Log` facade `getFacadeAccessor()` method returning `log`, while in the `Application.php` we have `Psr\Log\LoggerInterface` instead.
This pull request fixes that.
> Fix Log resolver

- src/Application.php
I'm a complete novice when it comes to PHP, so this pull request is probably garbage, but here goes...
I've migrated a Laravel app to Lumen and one of the side effects was that `error_reporting` changes were ignored.
For example, I had something like this:
```php
error_reporting(E_ALL ^ E_DEPRECATED);
// Use a legacy package that would normally trigger a PHP deprecated warning
deprecated_package();
error_reporting(-1);
```
Even if I would temporarily disable deprecated warnings, Lumen would still catch them and report them (and break the app). In Laravel it worked.
Laravel seems to [check `error_reporting` level before throwing an exception](https://github.com/laravel/framework/blob/89fcc958286c4105fbe24bf103f6c4d1fc2d6a5e/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L55-L58). …
> Check error_reporting before throwing ErrorException

- src/Application.php
Replaces laravel/framework#8513
> Register facades for command, useful for migration commands.

- config/database.php
When deploying the redis server is not always on the same machine, added environment vars to set the location of the redis server
> Added env to redis connection

- .gitignore
The environment configuration file can be ignored from Git.
> Added .env to .gitignore

- src/Application.php
- tests/FullApplicationTest.php
*Fixes #66*
This removes trailing slashes before routing by using `trim` instead of just `ltrim`.
I've also noticed that all existing unit tests used the Symfony Request class so I added two new tests. One that tests a basic request and another (previously failing) test to make sure trailing slashes are stripped correctly.
> Fix trailing slash

- src/Application.php
Because of [this change](https://github.com/laravel/framework/commit/27b1d17a420b4556a261c6f7a49115a90edd1018) the parameter has to be type hinted as array for the declarations to match.
> Type hint parameter to match the changes in contract

- src/Application.php
- tests/FullApplicationTest.php
Update code for parsing route middleware to ensure that everything will work correctly with middleware parameters in Laravel 5.1. Note that the unit tests will pass as soon as PR #72 is merged.
> Get Lumen routing ready for middleware parameters

- src/Application.php
Uncommenting the `$app->withFacades()` call in the bootstrap/app.php file isn't enough to use `Hash` facade.
> Register Hash facade

- src/Application.php
- tests/FullApplicationTest.php
Hopefully you can merge this one Taylor. Not a big change by any means. Just allows a little more flexibility with the routing by letting me register a custom dispatcher... You know what for!
Cheers mate.
Signed-off-by: Jason Lewis <jason.lewis1991@gmail.com>
> Allow developers to register their own FastRoute dispatcher with the app.

- src/Routing/UrlGenerator.php
- tests/FullApplicationTest.php
*Issue #70*
This PR makes generating an URL for a named route behave more like in Laravel. Parameters that don't exist in the route itself will be appended as GET parameters.
While implementing this I also found a bug in generating URLs for regex routes. Before this PR route parameters where replaced if the parameter only began with the passed name. For example:
Route: /foo/{bar} - Name: foo
route('foo', ['b' => 'hello']);
=> /foo/hello
This is fixed now and only one call to `preg_replace_callback` is needed.
Sorry I couldn't split the bugfix and the other stuff in two PRs since it all concerns the same method...
> Add query strings to URL generator and fix parameter bug

- src/Application.php
This is in response to #87.
The idea is that the routing behave in a similar manner to that of L5. Currently, Lumen will look for a route first before it tries to pipe the request through the middlewares.
Laravel 5 will pipe the request through the middlewares first and then find and dispatch the route.
Obviously they both do routing a little differently, however, I think this difference is a bad one and can lead to some unexpected results. As it stands a global middleware in L5 will always be run even if the route does not exist. That's expected behaviour to me. In Lumen, the global middleware will never run if the route does not exist.
This PR fixes that by piping the request through the middleware first.
This was going to be my biggest concern, however, it seems the change doesn't …
> Tweak Application Routing

- src/Application.php
Created a new PR as requested by Taylor to check if the response is a BinaryFileResponse. If the response is, then it is prepared before sending the download to the user. This prevents less overhead with "normal" requests while fixing an "issue" with the download() functionality. The PR is in reference to this PR https://github.com/laravel/lumen-framework/pull/102 *AND* this issue https://github.com/laravel/lumen-framework/issues/74
Thanks!
> Checked if response is an instance of BinaryFileResponse and returned a prepared response

- src/Routing/ValidatesRequests.php
`Validator::make()` has the 4th param `$customAttributes` and it's so useful.
In case of Controller Validation, `$this->validate()` doesn't work with it.
The simplest solution is just to add `$customAttributes` param to `ValidatesRequests::validate()`.
> Add custom attributes param for Controller Validation

- src/Application.php
Correct routing uri when
- ['prefix' => '']
- ['prefix' => '/']
before not found because double slash start uri generated.
ex) '//path/to'
> Correct $uri when ['prefix' => ''] and ['prefix' => '/'].

- src/Application.php
I'm not sure if this was left out intentionally or not but as it stands I can't inject an instance of the config repository, so here we go. :+1:
> Add container alias for Illuminate\Contracts\Config\Repository

- src/Routing/Controller.php
PHP Fatal error:  Trait 'Laravel\Lumen\Routing\DispatchesCommands' not found
> Fix for fatal error with renamed DispatchesCommands trait

- src/Routing/UrlGenerator.php
I noticed that `route()` does not support the `UrlRoutable` interface. This is a first attempt to add it.
> Add support for UrlRoutable to route()

- src/Application.php
This PR undoes https://github.com/laravel/lumen-framework/pull/32 and is to ensure the default `Application::basePath` is set to the application root dir.
By using the  `lumen new` command to instantiate a new project, the directory structure nests index.php under `root/public` and therefore `getcwd()` returns one level too deep for the app to access the `root/storage` dir.
For more info on the issue: https://laracasts.com/discuss/channels/general-discussion/why-the-app-basepath-is-the-public-folder
> set correct basePath when running cli-server

- src/Testing/CrawlerTrait.php
Not testing the response when we have data, means that an invalid JSON response results a confusing error:
```
1) AccountTest::testBasicCreate
ErrorException: Invalid argument supplied for foreach()
<project-dir>/vendor/illuminate/support/helpers.php:534
<project-dir>/vendor/laravel/lumen-framework/src/Testing/CrawlerTrait.php:311
<project-dir>/vendor/laravel/lumen-framework/src/Testing/CrawlerTrait.php:298
<project-dir>/xero_api/tests/endpoints/AccountTest.php:66
<project-dir>/xero_api/tests/endpoints/AccountTest.php:16
<project-dir>/phpunit/phpunit/src/TextUI/Command.php:151
<project-dir>/phpunit/phpunit/src/TextUI/Command.php:103
```
After this fix an invalid JSON response results in:
```
Failed asserting that JSON returned [http://localhost/account/1].
Failed asserting that '<!DOCTYPE …
```
> Assert response is JSON even when data is passed

- phpunit.xml
Hi,
The `syntaxCheck` parameter do not exist. So we can delete it.
https://phpunit.de/manual/current/en/appendixes.configuration.html
Regards
> [phpunit]: delete unused syntaxCheck parameter

- src/Application.php
Add 'cache.store' binding in Application:registerCacheBindings() - to resolve ReflectionException.
---
Closes #161.
> [5.1] Fix Cache Store Resolution

- src/Application.php
Closes #165
We can hardcode the namespace because there is no `app:name` command in Lumen, right?
> [5.1] Fixes #165

- src/Routing/UrlGenerator.php
- tests/FullApplicationTest.php
Little fix that will get rid of trailing curly bracket in case of using regex to check parameter length.
Without that generating route from something like `/test/{param:[0-9]{5}}` will lead to `/test/5}` (as you can check by running added test without fixed regex).
> Curly brackets in route regex

- src/Testing/CrawlerTrait.php
This was added to Laravel in [laravel/framework#9265](https://github.com/laravel/framework/pull/9265) and it would be great to see it in Lumen as well.
> Add dontSee() to CrawlerTrait

- composer.json
I think it's much safer to update this in the next minor version. Updating this in a patch release might actually cause issues with dependency conflicts for people, preventing them receiving newer Lumen 5.1 releases. 0.6 might also have unexpected breakages since 0.4 and if people have been messing with route caching, which they might have been because custom Lumen setups can't be that uncommon.
TLDR: 5.2 is a much safer place to make this change than 5.1.
> [5.2] Updated Fast Route

- src/Testing/CrawlerTrait.php
The `array_sort_recursive()` helper was updated recently (actually the `Str` class method it points to was.  Now it has uncovered this issue (I presume because it is working better than previously).
The `seeJsonContains()` method uses `json_decode` on the response content passing in a value of `true` for the second param, which of course typecasts all objects to arrays.  If the response content is getting all objects typecast to arrays recursively, then the data array passed into the function should get the same treatment.
This wasn't causing an issue before the `array_sort_recursive()` update.  I presume that the nested arrays are now getting sorted properly and causing the objects not to match.
> [5.1] Recursively transform data to array

- src/Application.php
- src/Routing/Controller.php
I ran into problems when trying to use behat with the [behat-lumen-extension](https://github.com/arisro/behat-lumen-extension) - the kernel was being loaded with a Symfony Request, but at one point in the lumen framework there was typehinting for the Illuminate\Http\Request, resulting in a fatal error.
The request object is never even used in that method or class though, so I thought it would be best to remove it completely. An alternative could just be to fix the typehint.
One other alternative could be to replace the Symfony request (that gets stored as Illuminate\Http\Request in the container) with the Illuminate equivalent using it's Request::createFromBase() method. I'm happy to change this either way as long as I can sort out the problem.
> Removing incorrectly typehinted request parameter

- src/Application.php
The middleware of a route should be appended to the middleware of it's group.
> [5.1] Append middleware of action to group middleware

- config/queue.php
Found out this bug when I tried to flush the queue, when I had pgsql as default db-connection.
> Set DB_CONNECTION env variable to Queue failed default database

- config/database.php
According to the docs, the sqlite database should be located within the "database" folder.
> Replace storage_path with database_path helper

- src/Exceptions/Handler.php
Good Evening!
I see that tests are currently failing on dev-master.  It appears that either the variable `$e` was meant to be `$fe` or the places in which `$fe` are used should be `$e` instead.
Take care,
Nicholas
> [5.2] Changed $e to $fe in render method.

- src/Routing/UrlGenerator.php
This would simplify generating asset when you need to specify different root domain/url as the request. Alternative to laravel/framework#10550 PR.
> [5.1] Generate a URL to an application asset from a root domain such as CDN etc.

- src/Application.php
Right now in order to get the configuration directory's path, you need to extend `Application` and access the `protected $appConfigDir` directly. This PR extends `getConfigurationPath()` to accept an empty string and return the config path in the case, and allow public access at the same time.
> [5.1] Allow getting path to configuration directory

- config/cache.php
To prevent cache key collisions when running multiple Laravel/Lumen apps on the same server, I would like to be able to customize the cache prefix.
> Provide ability to customize the cache prefix

- config/auth.php
Eloquent is disabled by default, so database is more suitable here.
> [5.2] Use database as default auth driver

- src/Application.php
This would make it slightly easier to re-add removed components in 5.2 in the Lumen bootstrap file such as.
```php
$app->singleton('view', function ($app) {
return $app->loadComponent('view', 'Illuminate\View\ViewServiceProvider');
});
```
> Change Application::loadComponent() method visibility to public.

- composer.json
This version has the new exceptions. I'd like to update the default app in 5.2 to catch these better like laravel/framework does.
> [5.2] Bumped suggested phpdotenv version

- composer.json
`App\Exceptions\Handler` uses `Illuminate\Validation\ValidationException` which is only available starting from 5.2.7.
> Bump requirement to v5.2.7

- src/Application.php
- src/Concerns/RoutesRequests.php
The `getRoutes` method has been removed as part of a [code cleanup](https://github.com/laravel/lumen-framework/commit/82adca8e67269498387fd0090037e6c40821ef99).
As it was used by [some Lumen packages](https://github.com/appzcoder/lumen-route-list) this PR brings it back.
> Brings back app()->getRoutes method

- src/Testing/Concerns/MakesHttpRequests.php
`seeStatusCode` method was removed during [5.2 code cleanup](https://github.com/laravel/lumen-framework/commit/b63c9525740082c68752efd4bb5aa421dda73213) that deleted `src/Testing/CrawlerTrait.php` file.
It seems to make sense to keep this method so unit tests can keep checking returned status code and response using fluent approach.
Implementation simply copied from Lumen 5.1.
Related to #310.
> Fluent syntax to see status code

- src/Application.php
Not possible to use cache on a fresh Lumen installation. ReflectionException “Class cache.store does not exist“ appears due to missing binding for 'cache.store‘. The following pull request should fix the issue.
> Fix missing binding for 'cache.store'

- src/Testing/TestCase.php
While mocking events and running phpunit the following error appeared due to the missing namespace declaration „Error: Class 'Laravel\Lumen\Testing\Exception' not found“. The following pull request will fix it.
> Adds missing \Exception namespace

- src/Exceptions/Handler.php
- tests/FullApplicationTest.php
5.2 changed the return type of `Laravel\Lumen\Exceptions\Handler@render` from an [Illuminate Response](https://github.com/laravel/lumen-framework/blob/5.1/src/Exceptions/Handler.php#L72) to a [Symfony Response](https://github.com/laravel/lumen-framework/blob/5.2/src/Exceptions/Handler.php#L93).
After upgrading to 5.2 my after middleware started failing because it was expecting an Illuminate response.
This PR restores the original behavior and returns an Illuminate response.  I added a simple test too.
Thanks!
> [5.2] Return an Illuminate response from the exception handler

- src/Application.php
- src/Concerns/RoutesRequests.php
Fixes issue #246.
I wrote a test but it won't pass unless I require --dev zend-diactoros and psr-http-message-bridge.  I didn't see them in the Laravel's composer.json so I left them out here.  Should I add them + the test?
> Add support for PSR-7 requests and responses.

- src/Concerns/RoutesRequests.php
When I run repeatedly `$app->run($request);` app recreate dispatcher on each `dispatch()`, which have bad behaviour on performance. For me 130ms(now) => to 22ms(fixed).
> Do not recreate dispatcher on every dispatch()

- config/cache.php
Without this entry, Lumen will throw `Cache store [apc] is not defined.`
> Add missing configuration for APC cache driver

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
Resubmitted to 5.2 branch as requested in https://github.com/laravel/lumen-framework/pull/352
------
Hello,
We were just looking at creating an API in lumen and noticed it would be really useful if we were able to specify a route suffix (in much the same way as the current route prefixes work). This would allow us to support users adding .xml/.json to the ends of our endpoints without us needing the repeat the regex for every route in our app.
Our own use case for the change looks roughly like:
```php
$app->group([ 'suffix'=> "[.{api_format:json|xml}]" ], function($app){
$app->get('/foo', 'BlaController@foo');
$app->get('/bar', 'BlaController@bar');
});
```
Which means `/foo`, `/foo.xml` and `/foo.json` endpoints are all valid for routes within the group.
Thanks,
Carl
> [5.2] Allow route suffix

- src/Testing/Concerns/MakesHttpRequests.php
It has been added to Laravel but not Lumen: 
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L252
> [5.2] Add wildcard support to seeJsonStructure

- config/database.php
Making the database schema configurable via an environment variable.
Useful when running multiple schema's for various reasons, such as simplified testing infrastructure by using a test schema.
> Add DB_SCHEMA as env variable for postgres

- config/auth.php
This reverts commit 2748c05c9d9bef64a0ec3ad4b119b1119833c408.
The commit in question breaks application using the lumen app skeleton. `api` is the defined provider through the first parameter in the [auth service provider](https://github.com/laravel/lumen/blob/master/app/Providers/AuthServiceProvider.php#L33). This means applications using the default will break with an `undefined index: providers` when attempting to just use the default service provider. We instead need to either revert this commit so the skeleton works (preferred method) or update the skeleton to use `token` instead of `api` for the `viaRequest` parameter.
> Revert "'API' isn't a supported driver"

- config/broadcasting.php
- config/cache.php
- config/database.php
- config/queue.php
Make as many env variables for config entries as possible. This allows developers to override things without reimplementing the config files in their application for minor edits.
Also some minor code style things for array alignment in the queue config.
> Expand env variables for all configs.

- config/database.php
Simply bring this default connection to feature parity with other database connection types.
Currently things fall apart when talking to nvarchar and similar fields in sqlserver when those fields contain UTF-8 data. The encoding will be off an you need to hack mb_* logic around the fields to resolve this. Other parts of lumen support passing the character set into the connection string when its supplied and supported by the connection library(freetds). However currently the default connection logic does not support supplying that character set the way other connections do so this adds that support.
> Support charset for sqlsrv connection

- config/database.php
psuedo backport #368
This mostly aligns the SQL Server connection with other connections that already supply a UTF-8 character set to their connections.
Currently things fall apart when talking to nvarchar and similar fields in sqlserver when those fields contain UTF-8 data. The encoding will be off an you need to hack mb_* logic around the fields to resolve this. Other parts of lumen support passing the character set into the connection string when its supplied and supported by the connection library(freetds). However currently the default connection logic does not supply the character set the way other connections do. This supplies a more reasonable default.
> Consistent charset for sqlserver connection

- src/Application.php
- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
The default route resolver and user resolver were only being set if a request was not passed in.  I.E., the resolver would work if you called `$app->run()`, but not if you called `$app->run($request)`.
This causes `$request->route()` and `$request->user()` to return null when running tests, even though they work fine the rest of the time.
> [5.2] Set Request resolvers when request is provided

- src/Testing/TestCase.php
This allows to specify a database connection on which to test database assertions like `seeInDatabase`
> Allow for giving a connection on which to assert database checks

- src/Concerns/RoutesRequests.php
At the moment Lumen will only set the route resolver on an external request (through the browser). That's because the route resolver (along with the user resolver) are only set when the request instance is resolved from the container without having already been bound.
When a request is dispatched and an actual request instance is passed in then the route resolver is never set, so `$request->route()` always returns `null`.
Is there a reason the resolver is set this way when Laravel sets it once the route has been found.
I don't expect this to get merged, at least, not like this. I think it should be considered though, as it's proving quite a pain within Dingo.
I suggest the route resolver is moved to this location, and we set up a `rebinding` somewhere for the `request` instance so we can …
> Set route resolver after route is found.

- src/Application.php
I assume it was a simple oversight that this line was missing.
> Register URL facade

- src/Application.php
Same as #381 except for 5.1.
Sets the route resolver on requests that are fired manually through the `dispatch` method.
> Set route resolver on request when route is found

- src/Application.php
It can be fixed through manually registering the binding in the `bootstrap/app.php`, but I think it supposed to be available as a default. Now you can type-hint `Illuminate\Database\ConnectionResolverInterface` in a Seeder class or anywhere people want.
See Issue #350, #51
> Fix injecting Database Connection Resolver

- config/auth.php
Error: `Class session.store does not exist` trying to authenticate with the `session` driver.
Note: `SessionGuard` is the only Guard with a `onceBasic` method
[Related Issue](https://github.com/laravel/lumen-framework/issues/388)
> Remove 'session' as supported option

- src/Console/Kernel.php
I'm whipping up a simple app where I won't need to extend the console in any way, and usually when there is a feature I won't be using, I rip out the folders to clean up the directory structure.
However, removing the `app/Console/Kernel.php` file (+ changing the container binding in the bootstrap file) currency breaks the Artisan CLI with this error:
Undefined property: Laravel\Lumen\Console\Kernel::$commands
This PR simply adds a default `$commands = []` property on the Console Kernel class. As a side note, the Console Kernel in the Laravel Framework _does_ contain a default `$commands` property.
Also, I feel that it _should_ be an option to use `Laravel\Lumen\Console\Kernel` without first extending it, as it is not abstract.
> [5.2] Default $commands in Console Kernel

- src/Concerns/RoutesRequests.php
This PR resolves route from request's routeResolver after piping it through middleware. It allows for middleware to override array based routeInfo by setting route resolver on request instance.
For example it makes possible to use implicit route model binding middleware like this (code taken from Lumen's big brother and adapted for array based route): [SubstituteImplicitBindings.php](https://gist.github.com/sw-double/bdc8285b61be5a8e064d)
> [5.2] Allow middleware to replace route info and route parameters

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
Instead of having to do:
```
$app->options('/', 'Controller@Action');
$app->get('/', 'Controller@Action');
```
Can just do:
```
$app->addRoute(['GET', 'OPTIONS'], '/', 'Controller@Action');
```
> addRoute now accepts multiple methods

- src/Testing/TestCase.php
If facades are not cleared first service providers using facades will boot with the old instance.
This is really hard to test without the concrete implemention of TestCase in Laravel/Lumen.  You can reproduce using these steps in a fresh Lumen install:
Add this to `AppServiceProvider.php`:
```php
Validator::extend('rad', function ($attribute, $value, $parameters) {
return str_contains($value, 'rad');
});
```
Add this to `routes.php`:
```php
$app->post('/', function (Illuminate\Http\Request $request) {
$this->validate($request, [
'mood' => 'rad'
]);
return json_encode(['hello' => 'world']);
});
````
Uncomment these lines in `bootstrap/app.php:
``php
$app->register(App\Providers\AppServiceProvider::class);
$app->withFacades();
``
Add this test to `ExampleTest.php`:
```php
public function …
```
> [5.2] Clear facades before bootstrapping the app

- src/Testing/Concerns/MakesHttpRequests.php
This method is important in lumen to be able to test that headers like
`Access-Control-Allow-Origin` are present on the response.
The implementation is copied directly from Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L402
> [5.2] Add seeHeader method to MakesHttpRequests trait

- src/Application.php
- tests/FullApplicationTest.php
This method is present on Laravel Application.php but was not in Lumen for some reason. I thought it might make sense to add this to Lumen as well.
In case you are wondering the the false on the test case, that is because we are not extending the TestCase which sets up the environment to "testing".
> [5.2] Adding runningUnitTests method to Application

- src/Exceptions/Handler.php
We don't want to suppress errors like when the file permissions are incorrect on the storage folder, for example.
> [5.2] Fixed incorrect logging error suppression

- src/Exceptions/Handler.php
We don't want to suppress errors like when the file permissions are incorrect on the storage folder, for example.
> [5.1] Fixed incorrect logging error suppression

- src/Application.php
Needed after we deleted the `__call` fallback in the main laravel repository.
This is now in sync with what the main framework does to setup providers.
> [5.3] Fixed service provider registration

- src/Application.php
Note how the default to register them when calling withFacades is true, but the default for the console booting is now false.
---
Closes #321.
> [5.3] Support not registering facade aliases

- src/Application.php
- tests/FullApplicationTest.php
This is in reference to #432.
If we want to add a new Facade to a Lumen application we have to manually add `class_alias` in the `bootstrap/app.php` file. However this might cause issues when using PHPUnit since it will include `bootstrap/app.php` more than once. This will result in an error since it is trying to register the `class_alias` again.
> Cannot declare class ExampleAlias, because the name is already in use
One way to fix that is to wrap each `class_alias` in a `if (!class_exists('Foo', 'Bar'))`. If I need to register multiple Facades this will lead to a lot of code duplication and clutter in my `bootstrap/app.php`.
For the default Facades Lumen already checks if the Facades have been registered yet. So my proposed fix is to add a second, optional parameter to the `withFacades` …
> [5.3] Allow user to register Facades within the `withFacades` method.

- src/Application.php
- tests/FullApplicationTest.php
The Illuminate\Console\AppNamespaceDetectorTrait throws an error when attempting to call the getNamespace method on the Container instance. Pulled this from `Illuminate\Foundation\Application` and added it.
> [5.2] Adds getNamespace to Application

- src/Testing/Concerns/MakesHttpRequests.php
The method seeHeader in MakesHttpRequests should display the correct "Expected" and "Actual" test output. Right now, it thinks that what comes back in the request is the expected header.
> [5.2] Update MakesHttpRequests.php to have correct seeHeader test output.

- src/Testing/TestCase.php
De-register the Dispatcher bindings so that the mocked version gets bound correctly.
> Update TestCase.php to resolve issue #207

- src/Testing/Concerns/MakesHttpRequests.php
This breaks the assertResponseStatus method.
> Revert "[5.2] Update MakesHttpRequests.php to have correct seeHeader test output."

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
**Issue 1**
The bug occurs when global middleware is assigned with parameters:
`$app->middleware(['LumenTestParameterizedMiddleware:foo,bar']);`
In `$app->run()` after the response is send, when `callTerminableMiddleware()` runs it will throw an exception because the full string with parameters is passed to `make()`, so you'll get:
> ReflectionException: Class LumenTestParameterizedMiddleware:foo,bar does not exist
So the simple fix for that is to trim off any parameters. However, there's already a test case for this that has been passing: `\FullApplicationTest::testGlobalMiddlewareParameters()`. This highlighted the fact that the `handle()` method used for testing is not a true representation of `run()`, because it never checks for and attempts to run middleware terminate methods.
Now …
> Middleware bug fixes

- src/Application.php
Which could lead to difficult to troubleshoot Segmentation faults when upgrading from 5.2, or if you added the BroadcastServiceProvider yourself to `bootstrap/app.php`. This could also be resolved by changing how the event dispatcher fires broadcasting events, but since this is a Lumen specific error, it seems better here.
Solves issue: https://github.com/laravel/lumen-framework/issues/500
Excuse my newness to open source. I hoped I haven't missed something obvious I should be doing.
> Fix loading broadcasting component via event dispatcher

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
Was working with routes in lumen today and had setup a group with namespace.
Inside that group i was also using another group to set some authentication middleware, and here comes the problem.
When i created routes inside the second group, none of the routes got the attributes from the first group.
The problem is also descripbed in #239 where the second group could not find the (expected) namespace for the controller.
As also mentioned in the same issue, the docs do show that you have to write the full namespace again, but this feels very bloated.
This PR includes
* Tests for
* nested `'as' => 'name'`
* nested `'namespace' => 'Hello'`
* nested `'middleware' => 'hello|world'`
* nested `'prefix' => '/hello'`
* Changing how groups works for lumen routes
This will be a breaking change since …
> Makes nested groups inherit previous groups attributes

- src/Testing/TestCase.php
Got this issue when testing on sqlite in memory config for testing.
Looks like Laravel Framework updated in that too https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Testing/TestCase.php#L99
Maybe this should be target to 5.2 too.
> [5.3] Migrations should run first in setUpTraits

- src/Concerns/RoutesRequests.php
If you try to return non symfony response from an exception handler (for example an array, or PSR-7 responses) you get an exception that the object could not be converted to a string (see [here](https://github.com/laravel/lumen-framework/blob/5.3/src/Concerns/RoutesRequests.php#L478)).
This is inconsistent with the behavior from controllers or invokable controllers who can return those types without problem because they are run through the prepareResponse method.
This small patch runs the responses from the exception handlers through the same function to allow consistent behaviour from controllers and exception handlers.
> Run responses from exception handlers through prepareResponse

- src/Application.php
- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
Prevents a type error when calling Application::handle with a Symfony Request.  Useful if you are using the PSR-7 bridge since it creates a Symfony request.
> Support HttpFoundation requests

- src/Testing/Concerns/MakesHttpRequests.php
I was thinking about reusing the `MakesHttpRequests` trait but found after poking through it an inconsistent approach to calls to PHPUnit's asserter. In some cases [it is being called non-statically](https://github.com/laravel/lumen-framework/blob/aa71978a2d855b862137b42883943930df54145e/src/Testing/Concerns/MakesHttpRequests.php#L186), while in other cases [it is being called statically](https://github.com/laravel/lumen-framework/blob/aa71978a2d855b862137b42883943930df54145e/src/Testing/Concerns/MakesHttpRequests.php#L390). I've converted all of these to static calls.
One issue still remains, however: this trait depends on several external properties:
```php
$this->baseUrl
$this->app
```
Is it alright to use the `app()` helper to get around this problem?
Unfortunately, I believe none of …
> Calling phpunit asserter statically from MakesHttpRequests trait

- src/Application.php
If you try to resolve the AuthManager it doesn't call the service provider
which results in a 'cannot resolve parameter app' error because Lumen
doesn't implement `Illuminate\Foundation\Application` and there isn't a typehint.
I'm using the AuthManager directly and not the factory contract because I need
to call `AuthManager@extend`.
> [5.4] Add AuthManager binding

- src/Concerns/RoutesRequests.php
Problem:
This won't work (in `routes.php`): 
```
$app->group(['namespace' => \Namespace'], function() use ($app) {
$app->get('my-route', 'MyController@index');
});
```
Error:
> Class App\Http\Controllers\Namespace\MyController does not exist
But it should work, because there is a heading backslash in namespace (it's a fully qualified name).
Solution: check backslash in the beginning of the string in formatUsesPrefix method before adding "old" namespace.
_Side note: Same problem fixed here: https://github.com/laravel/framework/pull/7859_
> [5.3] Accept FQN for controller in namespaced group

- src/helpers.php
The $event variabel accepts both strings and objects. This should be mentioned within the functions documentation.
Some of my code inspections fail because I insert an object (which is possible).
> new \App\Events\MyEvent.......) is of type object<App\Events\MyEvent>, but the function (event) expects a string.
> Update event docblock

- src/Application.php
- src/Concerns/RoutesRequests.php
While running tests, the `Request` singleton causes the instance registration not to be considered while calling `parseIncomingRequest()`.
In this PR I drop the usage of `singleton()` and register the instance from within `parseIncomingRequest()`, that way the request we get from `Request::capture()` will only be used in normal HTTP requests, while in unit tests the Request we create while using `call, get, post...` will be used.
> Properly create a Request instance to fix tests

- src/helpers.php
I was profiling a large lumen application and realized that the app was spending a lot of time in the UrlGenerator.
Because the `route` and `url` helper functions don't resolve the UrlGenerator from the container, the scheme and root are never cached.  Since they aren't cached the UrlGenerator resolves the request every time.
This PR changes the helper functions to use the container, since the UrlGenerator is bound as a singleton.  On an endpoint that generates a lot of links this made it 20% faster.
> Always resolve the UrlGenerator from the container

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
Now that #558 is merged, we always create a Request instance before routing.
Since we have a request instance, we can go ahead and use that to get the current method and path, which fixes #533.  Calling `getPathInfo` and `getMethod` only takes ~.1 nanosecond so it shouldn't affect performance.
I also made sure `prepareRequest` is always called so that the route resolver and user resolver are set.
It looks like the path when you weren't using the Request class was trimming the trailing slash, but that doesn't happen when using a Request.  It doesn't look like the full Laravel framework trims trailing slashes so I kept it as is.
> Always get the method and path from the Illuminate Request

- src/helpers.php
Ports the fix from laravel/framework#17614 to Lumen.
This fixes calls to the `factory()` helper which don't specify an amount returning a Collection of a single element (because of laravel/framework#17493), when they should be returning the model instance itself.
> [5.4] Default to null if amount isn't set in factory helper

- src/Testing/Concerns/MakesHttpRequests.php
This PR fixes the issue of the json parameters not being loaded in tests that use the `json` call.
The function `getInputSource` is called in the `Request::createFromBase` which loads the json on the Request but that does not happen when the request is created straight using `SymfonyRequest::create`.
Fixes #522, #55
> Fix json parameters not loaded in tests for `json` calls

- src/Application.php
- src/Exceptions/Handler.php
Since the Lumen Framework doesn't have the `config:cache` support from Artisan, I had to use `CONFIG` instead of `ENV` for some good and important reasons.
The framework uses `ENV` to set the `APP_ENV` and the `APP_DEBUG` currently. However, as I said, we may have other scenarios.
`// Application.php`
`$env = env('APP_ENV', 'production');`
`// Handler.php`
`$handler = new SymfonyExceptionHandler(env('APP_DEBUG', false));`
In this case, the framework should verify both.
`// Application.php`
`$env = env('APP_ENV', config('app.env', 'production'));`
`// Handler.php`
`$handler = new SymfonyExceptionHandler(env('APP_DEBUG', config('app.debug', false)));`
Thank you.
Based on https://github.com/laravel/lumen-framework/issues/417
Also must see
https://github.com/laravel/lumen-framework/issues/585 …
> Environment detection

- config/queue.php
`broadcasting.php` and `cache.php` are loading `BROADCAST_REDIS_CONNECTION` and `CACHE_REDIS_CONNECTION` to make them configurable in .env, but `queue.php` is not. It's better and helpful to make them consistent.
https://github.com/laravel/lumen-framework/blob/5.4/config/broadcasting.php#L40
https://github.com/laravel/lumen-framework/blob/5.4/config/cache.php#L61
> Make Redis connection for queues configurable in .env

- src/Application.php
change reason:
When development or deploy the php application, the devops may be set the php.ini file with config field  `date.timezone` in right value,hens we can check whether the .evn file setted APP_TIMEZONE to change date default_timezone,otherwise We need to change it when __construct at once.
> change Application.php __construct function date_default_timezone_set on customize

- src/Testing/Concerns/MakesHttpRequests.php
Fixes #609 
The `seeJsonContains` method used to reference `PHPUnit_Framework_Assert` instead of `PHPUnit\Framework\Assert`
> Fix a bug with MakesHttpRequests

- src/Testing/TestCase.php
This is basically a copy of laravel/framework#20606 but in lumen.
From the pull request laravel/framework#20606:
> Fixes an issue where tests that use mockery expectations that don't have any assertions are marked as risky.
> 
> mockery/mockery#376
> GrahamCampbell/Laravel-TestBench@981289c
> Add mockery expectations to the assertion count

- src/Application.php
This add support for the `Route` facade.
Now that [Lumen 5.5](https://github.com/laravel/lumen-framework/pull/647) includes a `router` object, we can support the `Route` facade.
> Add Route Facade

- src/Console/ConsoleServiceProvider.php
Fixes #655
As per the issue, artisan does not work because the signature of the Illuminate\Cache\Console\ClearCommand constructor has changed between 5.4 and 5.5. This fix is based on [Illuminate\Foundation\Providers\ArtisanServiceProvider](https://github.com/laravel/framework/blob/d35e24c409598c231371369dabc8cdc8c92a11d6/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php#L216)
> Fix console service provider clear cache command

- composer.json
Updated `mockery/mockery` to `~1.0` and `phpunit/phpunit` to `~6.0` to match Laravel Framework [composer file](https://github.com/laravel/framework/blob/5.5/composer.json).
> [5.5] Updated dev dependencies in composer.json

- src/Routing/UrlGenerator.php
During url generation we do not look for forced scheme. 
The getSchemeForUrl function should use the getScheme function in order to determinate the appropriate url scheme.
> Fix forced scheme url generation

- src/Http/ResponseFactory.php
Responsefactory should not convert the data to an array as JsonReponse will convert the data to an array if necessary before conversion to JSON. JsonResponse needs the original object data to do proper conversion to Json, using the toJson() method on Jsonable objects.
By not converting Jsonable data to an array, setData() in Illuminate\Http\JsonReponse will correctly call toJson() on the data.
In the old behaviour, ResponseFactory would convert to an array, and JsonResponse's setData() would just call json_encode() on it.
> [5.5] Don't convert Jsonable data for JsonResponse prematurely

- src/Routing/ProvidesConvenienceMethods.php
When the `dispatch()` function is available via `ProvidesConvenienceMethods` I would assume that I can also access the `dispatchNow()` function.
> Provide dispatchNow along with dispatch function

- src/Exceptions/Handler.php
This PR adds the exception to the logger context array when it is caught by the app's exception handler.
This makes it simple to send exceptions to a service like Sentry using the monolog handler since the exception key is documented in the PSR-3 docs and most handlers check for it.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#13-context
> Include the exception in the logger context

- config/database.php
Hi, is it possible to add the default client to redis in the default configuration. for more visibility
> Add default client in redis configuration

- src/Routing/ProvidesConvenienceMethods.php
When I use validate in lumen, it will return all data in request, but laravel only return request data in rules, so change it to keep same with laravel
> Keep validate method return only with rule items

- src/Routing/Router.php
FastRoute will fall back to GET when a HEAD method is not defined for a route, but there are occasions where a HEAD method may need to be handled separately from a GET route.
> [5.6] Router: Add support for head method

- src/Application.php
Since 5.6 the `Illuminate\Mail\Mailable::send()` requires the Translator to work.
Without an alias to its contract, it breaks the things.
> Add translator alias

- composer.json
Updates expression package from `mtdowling/cron-expression:~1.0` to
`dragonmantank/cron-expression:~2.0` to match `laravel/framework`.
Tests pass but I didn't look to see if there was any coverage on the CRON expressions.
> Updates cron expression to match Laravel

- src/Console/Kernel.php
In a console environment there was no Request object. This caused problems with url generation during testing, and artisan commands.
Hopefully fixes #513 and #667.
> [5.6] Add console request for url generation

- src/Console/Kernel.php
The change made into #739 bind request into the container regardless if a request has been already bound or not which has for result to give an empty request to my `viaRequest` closure in `AuthServiceProvider` so I'm not able to authenticate any user from the request anymore.
This fix bind the request into the container only if no request has been bound before.
> [5.6] Console Kernel: bind request into container only if not already bound

- src/Testing/Concerns/MakesHttpRequests.php
This PR resolves #745 
When making request calls in tests it uses applications (console) request but that has been replaced in this commit c86cc51b88095b0dea06fc0c4d837abfe1264971
PR adds request object to application thats being built when test calls request.
> [5.6] Fix to use request object when calling requests on testing

- src/Application.php
The runningInConsole functions of Lumen are Laravel are currently different to each other. This means PHPUnit code coverage using phpdbg cannot be achieved with Lumen, but can with Laravel.
Please refer to https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Application.php#L518 to see this functionality in Laravel 5.6.
> [5.6] Added phpdbg to runningInConsole to bring in line with Laravel

- src/Testing/WithoutEvents.php
- src/Testing/WithoutMiddleware.php
The `WithoutEvents` and `WithoutMiddleware` traits are referenced in [`Laravel\Lumen\Testing\TestCase`](https://github.com/laravel/lumen-framework/blob/5.6/src/Testing/TestCase.php#L90-L96) but the traits themselves are not included in the Lumen Framework.
> Add Missing Testing Traits

- src/Application.php
The new `LogManager` [expects the `env` binding to exist](https://github.com/laravel/framework/blob/6a88b98e58f92ca1928175291ca0259db3704db0/src/Illuminate/Log/LogManager.php#L393).  If it isn't set everything get's logged as 'production', like this:
```
[2018-05-24 20:46:16] production.INFO: hello world
```
This PR adds the `env` binding when the container is bootstrapped so the logs return the correct environment.
```
[2018-05-24 20:46:53] local.INFO: hello world
```
> Bind the app environment as 'env'

- src/Testing/Concerns/MakesHttpRequests.php
PHPUnit\Framework\Exception: Argument #2 (No Value) of PHPUnit\Framework\Assert::assertArrayHasKey() must be a array or ArrayAccess
> [5.6] Fixes condition to json_decode responseData

- src/Application.php
Same problem as described here:
https://github.com/laravel/framework/issues/21015
For me, the effects look as follows:
Before:
```
Time: 8.16 minutes, Memory: 510.00MB
OK (1112 tests, 3677 assertions)
```
After:
```
Time: 8.08 minutes, Memory: 140.00MB
OK (1112 tests, 3677 assertions)
```
> [5.6] Fix memory leak for tests

- src/Console/Kernel.php
If the url helper or generator is used in a command line based request, it will return the wrong url. This problem occured in Laravel a while ago. Someone fixed this problem and the fix was also implemented in Lumen. ( laravel/framework#14139) 
The fix was implemented in the `kernel.php` in the `Console` directory. The fix currently is implemented like this:
```php
if (! $this->app->bound('request')) {
$this->setRequestForConsole($this->app);
}
```
The `setRequestForConsole`, however, will never be called because the request is bound on every request. Console or not. The request alias is registered in the `registerContainerAliases` method in the `Application`. This method is called in the `bootstrapContainer` method which is called in the constructor of `Application` class. And the …
> [5.7] The url helper generates the wrong url, when used in a queue.

- src/Testing/TestCase.php
Due to some new changes in Lumen, the application only boots within the `RoutesRequests` class. This pull requests ensures that the app will also boot when it's in testing mode.
#808
#806
> [5.7] Boot the application in the testing environment.

- src/Http/ResponseFactory.php
The phpdoc currently specifies either string or array, but the data parameter of json can be a variety of types in lumen/laravel.
See also upstream parameter definition in: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Http/JsonResponse.php#L23
and consuming implementation: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Http/JsonResponse.php#L56
This helps code to pass in larastan.
> Correct phpdoc of JsonResponse data to mixed type

- composer.json
After https://github.com/illuminate/support/commit/98cf3233c2e4a54c9aeba661e0ec40ccc3285dc0 the `dd` helper no longer exists in Lumen.
This pull requests adds the `symfony/var-dumper` to the framework's `composer.json` and brings the helper back.
> Include Symfony VarDumper component

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
> This PR fix #667.
When testing and making a request to a specific route, inside the Controller action, using the method injection for Request, I get all the information I need:
```php
public function login(Request $request) // $request OK
```
But inside the `Resource` object, in all methods I receive it as a parameter, like `toArray($request)` or `with($request)`, this `$request` object is empty, no route information, no parameters, no path, nothing.
Then I have to get the request again from the service container:
```php
public function with($request) // empty
{
$request = app(Request::class); // correct
return $request->is('auth/login') && $this->jwtToken ?
['token' => $this->jwtToken] : [];
}
```
When implementing the `Responsable` interface we send a new request instance by using …
> Change Request instance for responses implementing Responsable interface

- src/Testing/DatabaseMigrations.php
**Issue:**
As described in issue #775  currently the DatabaseMigrations trait doesn't revert database migrations after a test correctly. It just rolls back the last migration so after the first test the database is populated and following tests might not work.
**Fix:**
I replaced the 'migrate' command with 'migrate:fresh' so the database will be fresh before each test.
This is also done in [PR in laravel](https://github.com/laravel/framework/pull/20090).
I think this can break tests although I don't know how the current implementation is working for someone.
Also, I don't know if the rollback after the test would still be necessary.
> Using migrate:fresh instead of migrate for DatabaseMigrations

- src/Concerns/RoutesRequests.php
All exceptions implement Throwable interface thus given catch statement is obsolete.
> [5.8] Removed obsolete catch

- src/Concerns/RoutesRequests.php
Lumen's `prepareResponse` returns the wrong HTTP protocol because the `prepare` method is not called. This PR prepares the reponse, so it will return the right protocol.
#449
> [5.7] Make sure the response uses the right HTTP protocol.

- src/Http/Request.php
This pull request fixed the fingerprint method in Lumen. I redeclare the fingerprint method in Lumen's extended Request class and replace the original calls with calls that are available in Lumen.
#348
> [5.7] Make the fingerprint method compatible with Lumen.

- src/Application.php
- tests/FullApplicationTest.php
This PR fixes the underlying issue that caused #207 and #416.  I have also seen this cause issues with [other packages](https://github.com/laravel-doctrine/orm/blob/5a004509adccc2cfc2143df6101852e2fab4a048/src/DoctrineServiceProvider.php#L96).  The specific example of `expectsJobs` was fixed by 16a452a but the underlying issue still exists.
If you register your own binding for something in [the availableBindings array](https://github.com/laravel/lumen-framework/blob/ad953771b534b4c1d01f1a3d84353428addcb270/src/Application.php#L906) before it's been resolved at least once, when you go to resolve it Lumen calls the service binder method and overwrites your binding.
To prevent this we can check if the binding has already been bound and if so we won't run the service binder this time.
The …
> Dont overwrite container bindings that have already been bound

- src/Testing/TestCase.php
- tests/FullApplicationTest.php
This was a workaround and is not necessary since 56277d4 was merged.
> [5.7] Don't unnecessarily unset available bindings

- config/filesystems.php
- src/Application.php
I propose to register Filesystem bindings by default to address issues like this https://github.com/laravel/lumen-framework/issues/168
> [5.7] Register Filesystem bindings by default

- src/Routing/UrlGenerator.php
- tests/FullApplicationTest.php
This pull request adds support for optional parameters in the route url generator. This pull request was made to solve #539.
I've added a new regex which captures the string between the last square brackets, so it won't conflict with the route regex functionality. Within that string the route parameter placeholders will be replaced by their actual parameters.
If the `preg_replace_callback` function could not find any matches it will return the original string. I use that functionality to determine whether any placeholders were replaced. If not, it will be removed.
> [5.7] Add support for optional parameters in the route generator.

- src/Application.php
Hi, i have a some problems with my custom `Application` which extends from base `lumen\Application` and setup in `bootsrap/app.php`.
```php
// Custom\Application.php with custom methods
class Application extends \Laravel\Lumen\Application 
// app.php as base setup
use Custom\Application;
$app = new Application(
realpath(__DIR__ . '/../')
);
```
This fix solve my problems and has back compatibility.
What do you think?
> [5.7] Change application instance

- src/Console/Kernel.php
Remove the "Schedule" class's constructor argument. The "Cache" instance was passed to the "Schedule" class, which is not needed anymore, since the dependency in the "Schedule" class was removed sometime ago.
This also fixes: #844
> [5.7]  Remove the "Schedule" class's constructor argument.

- src/Application.php
- tests/FullApplicationTest.php
See https://github.com/laravel/lumen-framework/pull/840. Added a test to verify the correct behavior.
> [5.7] Fix overwriting the Application class

- src/Testing/Concerns/MakesHttpRequests.php
`PHPUnit::assertEquals` first parameter should be the expected not the actual one
> [5.7] Fix equals expected and actual order in seeHeaders

- src/Routing/Router.php
- tests/FullApplicationTest.php
At the moment lumen router is always appending namespace to route's "uses" defined controller.
Current example:
By defining UsersController lumen will apply default namespace from app.php "App\Http\Controllers"
```php
$router->get('profile', [
'as' => 'profile', 'uses' => 'UsersController@index'
]);
```
And in final output you will get ```App\Http\Controllers\UsersController@index```
If extra groups were defined, they will also append their namespaces.
This change allows user to override default namespace appending, by defining class name in global namespace:
Example after PR:
```php
$router->get('profile', [
'as' => 'profile', 'uses' => '\App\Http\Api\V1\Controllers\UsersController@index'
]);
```
In this example router won't append default namespace.
This makes lumen router to act same …
> [5.7] Ability to define FQCN class names in routes file.

- src/Concerns/RoutesRequests.php
- tests/FullApplicationTest.php
This PR rebinds the request after dispatching through middleware and before dispatching to the router, in the same way that Laravel does.  Resolves #856.
> [5.7] Rebind the request instance after dispatching through middleware

- src/Testing/TestCase.php
When the line setting the root URL was added, this forced use of the APP_URL env var, instead of using the same value that we can set in `config/app.php`, which can be any name for the environment variable. So if you had a different variable name such as BASE_URL (I suspect this is an artifact of an older version of lumen), and used that to set the `url` value in the app config file, the tests no longer worked, because the tests force you to use APP_URL. 
This change would default to whatever is set in app.php, with a fallback to the APP_URL value.
> [5.7] Support app config for URL, with env var fallback

- src/Routing/UrlGenerator.php
It was deprecated to be inline with Laravel `UrlGenerator`
> [5.8] Remove deprecated methods.

- src/Testing/Concerns/MakesHttpRequests.php
When testing, the `call` method provides an instance of the Laravel Request class while this should be Lumen's own Request class.
Fixes https://github.com/laravel/lumen-framework/issues/881
> [5.7] Fix incorrect request type during testing

- src/Console/Kernel.php
In Laravel 5.8 `Illuminate/Contracts/Console/Kernel` had the `terminate` method added. Updated Lumen's Kernel to match this addition.
> [5.8] Updated Lumen kernel to match the 5.8 kernel contract

- src/Console/ConsoleServiceProvider.php
In Laravel 5.8 the `$defer` boolean property on the provider is deprecated. Marking the provider as deferred now works via the `Illuminate\Contracts\Support\DeferrableProvider`contract.
https://laravel.com/docs/master/upgrade#deferred-service-providers
> [5.8] ConsoleServiceProvider implement DeferrableProvider contract

- src/helpers.php
In laravel 5.8 method `fire` [was removed](https://github.com/laravel/framework/pull/26392), but lumen helper uses it.
```
event(new SomeEvent());
// PHP Error:  Call to undefined method Illuminate/Events/Dispatcher::fire()
```
> [5.8] Fix event dispatching in `event` helper

- src/Testing/TestCase.php
When mocking events it is still checking if the fire method is triggered but this method has been deprecated since Laravel 5.4 and removed since 5.8 so the test passes while the code will fail.
> [5.8] Removed should receive 'fire' from expectsEvents and withoutEvents

- src/helpers.php
DotenvFactory only accepts instantiated adapters.
Also re-ordered to be the same as the Laravel implementation.
> Fixed PutenvAdapter in env helper

- src/Http/ResponseFactory.php
Removed the unnecessary semi column from the documentation. VSCode intelephense complains about it and PHP7 return type feature can't be used because putting semi-column in there is not syntactically correct.
P.S I already removed it locally, and it works like a charm.
Screenshot of mentioned issue: https://ibb.co/zn61dsV
> [5.8] Removed annoying semi column from json method.

- src/Application.php
- tests/FullApplicationTest.php
Lumen adds the filesystem factory as an available binding but as there is no alias the resolution fails.
https://github.com/laravel/lumen-framework/blob/32fa445283c182960891f4f21355376cf0ea3b31/src/Application.php#L937-L938
> [5.8] Allow filesystem factory to be dependency injectable

- src/Http/ResponseFactory.php
- tests/Http/ResponseFactoryTest.php
The stream method creates a streamed response. A streamed response
defers content generation until the output is needed. It is useful
e.g. for large or long-running responses that could be incrementally
consumed by clients.
The implementation matches Illuminate's ResponseFactory contract
(Illuminate/Contracts/Routing/ResponseFactory).
> Implement stream method in response factory

- composer.json
`vlucas/phpdotenv` was introduced as a dependency in #879, but is not included in `require`. This causes a PHP "Class not Found" Fatal Error. 
This PR adds the dependency to `require` to solve the issue. 
The tests were not catching this because the dependency was in `require-dev`. 
Fixes #918
> [5.8] Add vlucas/phpdotenv as a dependency

- src/Application.php
Allow `filesystem.cloud`, `Filesystem.disk` and their contracts to be retrievable with the service container. I've been doing some work with s3 lately and realised these were missing.
I'm not aware of any way of testing this as there aren't any filesystem drivers installed out of the box, any advise on adding tests?
> [5.8] Implemented Filesystem Cloud/Disk

- resources/lang/en/validation.php
Added validation language lines to the English language resources file to provide default validation error messages for validation rules that were missing them.
No logical changes made, just extra elements in the existing array.
> [5.8] Include validation language lines for rules missing them.

- src/Application.php
laravel/passport [commit](https://github.com/laravel/passport/commit/e260c865c218f00e4ad0c445dc45852e254d60c7) has added `configurationIsCached`, so lumen must have this that return a `false`
Best regards
> [5.8] Add the configurationIsCached method

- src/helpers.php
Added the missing broadcast method in helpers.php as it's available in Laravel's framework helpers. Fixes #947 .
> [5.8] Added broadcast helper function from Laravel's main framework

- src/Exceptions/Handler.php
This adds support for using the `report()` and `render()` methods on exceptions which is in [the documentation](https://laravel.com/docs/errors#renderable-exceptions) but not currently implemented in Lumen (as mentioned in #873).
This allows the exception handler class to check for an existing `report` or `render` method on the exception, mostly the same way as in Laravel's core handler ([report](https://github.com/laravel/framework/blob/7d2a5d0d9f6b4cc63840c24d555c1eef01c56b47/src/Illuminate/Foundation/Exceptions/Handler.php#L106-L108) and [render](https://github.com/laravel/framework/blob/7d2a5d0d9f6b4cc63840c24d555c1eef01c56b47/src/Illuminate/Foundation/Exceptions/Handler.php#L174-L176)).
It also adds support for exceptions that implement the …
> [5.8] Add support for reportable, renderable, and responsable exceptions

- src/Console/ConsoleServiceProvider.php
Fixed the required Cache parameter for the QueueRetryCommand, QueueRestartCommand and QueueWorkCommand instantiated objects.
Register the db:wipe command as it is used by migrate:fresh
> [6.x] Fix the required Cache implementation parameter and db:wipe command registration

- src/helpers.php
In Laravel 6.x, the `Illuminate\Contracts\Translation\Translator::trans()` and `Illuminate\Contracts\Translation\Translator::transChoice()` methods were renamed to `get` and `choice`.
See: laravel/framework#29529
Closes #974
> [6.x] Update references to translation methods

- config/database.php
The same changes as in the Laravel 6.0.
During the upgrade process to Lumen 6.0 you are suggested to remove **predis** in favor to **phpredis**. But after removing `predis/predis` you get errors because Lumen has hardcoded predis in configs. This PR is made to fix it.
> [6.x] Change the default redis client

- config/logging.php
Include a new null logging channel for Lumen as also included for Laravel in https://github.com/laravel/laravel/pull/5106
> [6.x] Add null logging channel

- config/cache.php
Update default redis cache connection to use this specific connection.
The cache connection is defined in databases config (https://github.com/laravel/lumen-framework/blob/6.x/config/database.php#L121)
> [6.x] Use redis cache connection by default

- src/Application.php
Add locale methods to `\Laravel\Lumen\Application`
Without this methods, the trait `\Illuminate\Support\Traits\Localizable` cannot be used, but the `\Illuminate\Notifications\NotificationSender`uses it.
> If notifiable uses `\Illuminate\Contracts\Translation\HasLocalePreference` the sender throws an exception:
> **Call to undefined method \Laravel\Lumen\Application::getLocale()**
Just copied methods from `\Illuminate\Foundation\Application` and removed the event dispatcher.
> Add locale support for application

- src/Application.php
load the app config before register DatabaseServiceProvider,
so that the configuration if faker_option can take effect when we create FakerGenerator
Close #989
> fix: make the faker_option in app config effective

- src/Exceptions/Handler.php
The previous license URL weren't working. So I just found new license URL from their new library [homepage](https://yuilibrary.com/)
License type is still same but the URL was dead.
> [6.x] YUI Library license fix

- src/Exceptions/Handler.php
The only correct place to look is within the config. It is only coincidental that the `app.debug` config entry is usually populated to whatever `env('APP_DEBUG)` is.
> [6.x] Stop inappropriate env lookup in exception handler

- src/Console/Kernel.php
- src/Testing/TestCase.php
The correct place to look is in the config file, which is what the code is already doing. There is no reason to read any environment variables. Setting the env variable will already set the value in the config file.
> [6.x] Removed more bad environment reading

- src/Application.php
Laravel uses bootstrappers to load env variables and setup the timezone. Lumen currently sets up the env from the app `bootstrap/app.php` file and sets up the timezone as a side effect of constructing the application. This feels like a bit of a hack to me, and I think this behaviour would be best placed in the `bootstrap/app.php` file too.
---
Related to https://github.com/laravel/lumen/pull/141.
> [7.x] Move timezone setting to app bootstrap file

- src/Routing/UrlGenerator.php
Safari for iOS supports SMS links: [See this link](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html)
> [6.x] Accept SMS Links as valid urls

- src/Application.php
Instead of getting expected error `'Unable to resolve PSR request. Please install symfony/psr-http-message-bridge and nyholm/psr7.'`, this error is shown instead: `Class 'Laravel\\Lumen\\Exception' not found in src/Application.php:524`
> Fix missing import

- src/Testing/Concerns/MakesHttpRequests.php
The typo causes errors in tests:
```
ErrorException: Undefined variable: status
/Users/user/project/vendor/laravel/lumen-framework/src/Testing/Concerns/MakesHttpRequests.php:424
```
> [7.x] Fixed a typo

- composer.json
Reverts laravel/lumen-framework#1049. Replaced by https://github.com/laravel/framework/pull/31988.
> [7.x] Revert "Add ramsey/uuid dependency, because of the illuminate/queue"

- composer.json
Even though Lumen references `illuminate/console` in it's code it doesn't directly depend on it. If `illuminate/queue` were to at some point drop it's `illuminate/console` dependency (I don't see why it would, but for argument's sake) Lumen would break.
> [7.x] Add illuminate/console as a dependency

- src/helpers.php
Add missing auth helper. This solves a problem with using the `@auth` directive in views.
Fixes https://github.com/laravel/lumen-framework/issues/1066#issuecomment-612878719
> [7.x] Add auth helper

- src/Application.php
Same as https://github.com/laravel/framework/pull/32349
As part of static analysis sometimes abstracts get resolved which aren't
resolvable => that's totally fine but it would help to use a common
exception to signal this.
> [7.x] Use BindingResolutionException to signal problem with container resolution

- src/Concerns/RegistersExceptionHandlers.php
Fixes https://github.com/laravel/lumen-framework/issues/1072.
> [7.x] Fixed typo in method name

- config/filesystems.php
AWS SDK doesn't really support the `url` config option, it needs to pass the `endpoint` option instead (https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#endpoint).
Related changes from upstream
- https://github.com/laravel/laravel/pull/5267
- https://github.com/laravel/laravel/pull/5276
This should fix the case where people try to use a S3 compatible service with the default configuration provided by the lumen framework. Otherwise, one needs to add a custom ServiceProvider that uses the appropriate config options.
> Fix S3 endpoint url reference

- src/Application.php
Follow up #1092 
Removing return because `register` method returns nothing.
> [7.x] Remove redundant return from void method

- src/Application.php
This PR is similar to https://github.com/laravel/framework/pull/33286
Here is how it works:
```php
if ($app->providerIsLoaded(OptionalServiceProvider::class)) {
// Do something
}
if (! $app->providerIsLoaded(RequiredServiceProvider::class)) {
// Throw exception
}
```
It might be useful in package development when you want to be 100% sure that provider is loaded. Or when you want to load some extra stuff if some optional providers are loaded.
Adding it to Lumen too because it will help us to avoid situations when package is working in Laravel, but not in Lumen:
https://github.com/laravel/framework/pull/33289#issuecomment-646965979
> [7.x] Add providerIsLoaded method to Application

- src/Application.php
- src/Console/ConsoleServiceProvider.php
- src/Routing/ProvidesConvenienceMethods.php
- src/Testing/TestCase.php
- src/helpers.php
- tests/Http/ResponseFactoryTest.php
This PR replaces string fully-qualified class names with `::class` notation and imports them if there are no naming conflicts. Didn't wanted to introduce aliases. I've added only `SymfonyResponse` alias in tests.
> [7.x] Replace string class names with ::class notation

- src/Providers/EventServiceProvider.php
This PR reordering `register` and `boot` methods in EventServiceProvider.
There are 2 reasons behind it:
1. `register` method is executing before the `boot` method
2. it's similar to the Laravel code base
> [7.x] Reorder register and boot methods

- .github/workflows/tests.yml
- composer.json
This PR will add php 8 support for Lumen 8.x. I used the same version constraints as in [Laravel 8.x](https://github.com/laravel/framework/blob/8.x/composer.json) for the relevant packages.
> [8.x] Add support for php 8

- src/Console/ConsoleServiceProvider.php
- src/Http/Request.php
- src/Routing/Pipeline.php
- src/Routing/ProvidesConvenienceMethods.php
- src/Routing/Router.php
- src/Testing/TestCase.php
None of these actually cause an issue for PHP 8 (unlike in laravel/framework), but never the less, we get better performance by not using those functions, and just using native calling syntax.
> [8.x] Avoid call_user_ functions

- config/cache.php
Cache clearing when using Redis would also clear the job queue as the default connection is used by both.
See https://github.com/laravel/laravel/blob/8.x/config/cache.php#L77
> [9.x] Default Redis cache connection is wrong

- src/Exceptions/Handler.php
Adding functionality that was present in 6.x to add headers to the response object in the exception handler, when the exception is an `HttpException`. This was a breaking issue for an application I develop for when I attempted to upgrade the Lumen version. It is not documented in the upgrade guide that this is new expected behavior.
> [8.x] Adding missing headers when exception is of type HttpException.

- src/Http/ResponseFactory.php
The following new add methods copy from [Illuminate\Routing\ResponseFactory](https://github.com/laravel/framework/blob/master/src/Illuminate/Routing/ResponseFactory.php)(laravel-framework-master)
```
// Create a new JSONP response instance.
public function jsonp($callback, $data = [], $status = 200, array $headers = [], $options = 0);
// Create a new streamed response instance as a file download.
public function streamDownload($callback, $name = null, array $headers = [], $disposition = 'attachment');
// Return the raw contents of a binary file.
public function file($file, array $headers = [])
```
These are very practical methods help building web applications easier.
> [9.x] Add methods for ResponseFactory class

- src/Exceptions/Handler.php
Use standard reporting when exceptions don't handle reporting by them self.
Inspired by laravel/illuminate exception handler:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/Handler.php#L228
> Use standard reporting when exceptions don't handle reporting by them self

- config/queue.php
When using artisan commands for creating failed jobs table the failed_jobs table is created with "database-uuids" format but default framework config expects different schema.
PR suggests to make things consistent with [laravel](https://github.com/laravel/laravel/blob/8.x/config/queue.php#L88) and save future developers [encountering](https://laracasts.com/discuss/channels/lumen/uuid-on-queue-failed-jobs-is-empty) this problem.
> make failed job default config consistent with table structure artisan command creates

- src/Http/Request.php
Removed `$route` within the `fingerprint` function, the local variable is not used anywhere.
> [8.x] Removed unused local variable

- src/Concerns/RoutesRequests.php
- src/Http/Redirector.php
- src/Http/Request.php
- src/Routing/ProvidesConvenienceMethods.php
- Replaced `@inheritDoc` -- missing parent member with doc comments 
- Updated docblock for `gatherMiddlewareClassNames` -- the `$middleware` parameter can handle arrays and the [`callLumenControllerWithMiddleware`](https://github.com/laravel/lumen-framework/blob/8.x/src/Concerns/RoutesRequests.php#L366) function passes an array
> [8.x] Fixed DocBlocks

- src/Routing/Router.php
```
laravel.WARNING: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/api/vendor/laravel/lumen-framework/src/Routing/Router.php on line 151
```
> [8.x] Fix PHP 8.1 deprecation issue

- src/Application.php
In this PR, I added `Illuminate\Config\Repository::class` class as alias for `config` to the list of registered container aliases.
---
I discovered that `app()->make(Illuminate\Config\Repository::class);` does not return proper instance of config class (empty config values), actually found in PassportServiceProvider.
https://github.com/laravel/passport/blob/10.x/src/PassportServiceProvider.php#L268
LaravelPassport uses `Illuminate\Config\Repository::class` class for getting config values, so in this case if we are using Lumen, config is empty.
https://github.com/laravel/passport/blob/10.x/src/PassportServiceProvider.php#L8
I think we can do the same as Laravel do:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Application.php#L1323
so …
> [8.x] Add Illuminate\Config\Repository::class as alias for config

- src/Application.php
According to the `Application` interface:
```php
/**
* Get the base path of the Laravel installation.
*
* @param  string  $path
* @return string
*/
public function basePath($path = '');
```
> Correct basePath() parameter

- src/Application.php
Fixes #1221. Same as #1222, but for 9.x, as 8.x is not supported anymore (where to find that information?).
> [9.x] Add langPath() method to Application

- src/Console/ConsoleServiceProvider.php
This PR fixes a bug in Lumen v9 which wasn't listing the schedule commands anymore. After some long digging I discovered this happened because the schedule commands were registered as classes rather than with string aliases. I have no idea why this fixes it though.
Fixes #1224
> [9.x] Fix schedule commands

- src/Console/Kernel.php
This is necessary for using native Laravel commands, such as _queue:prune-batches._
> Set ContainerCommandLoader for lazy loading console commands

- src/Testing/Concerns/MakesHttpRequests.php
Static analysis of a method using `call()` fails with the following error:
```
------ ----------------------------------------------------------------------------------------------------------------------------------------------------- 
Line   src/Testing/MakesGraphQLRequests.php (in context of class Tests\Unit\Testing\TestingTraitDummy)
------ ----------------------------------------------------------------------------------------------------------------------------------------------------- 
100    Method Tests\Unit\Testing\TestingTraitDummy::multipartGraphQL() should return Illuminate\Testing\TestResponse but returns Illuminate\Http\Response.
------ -------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Fix `MakesHttpRequests::call()` return type

- src/Console/ConsoleServiceProvider.php
Simply link the command into the service provider to make it available.
We need this commands to run the scheduler into our Kubernetes clusters. Current options of using "php artisan schedule:run" isn't working for us beacause we have a lot of microservices needing cron job and it was creating to much load on our master node.
Thanks
> Add missing Schedule:work command

- src/Routing/ProvidesConvenienceMethods.php
> Change controller validate helper method to behave like Laravel (#1247)

- src/Application.php
https://github.com/laravel/lumen-framework/issues/1250
> [9.x] Fix Call to undefined method Laravel\\Lumen\\Application::getFallbackLocale()

- src/Application.php
- src/Concerns/RoutesRequests.php
- src/Console/Kernel.php
- tests/FullApplicationTest.php
This pull request addresses https://github.com/laravel/lumen-framework/issues/1252, by ensuring `Application::terminating` is implemented and that it gets called on the console and HTTP layer.
Note, one difference between Lumen / Laravel on this implementation, is that the console `handle` is calling the `$app->terminate` on its `handle` method, as we can't modify the the `artisan` binaries that already exists on the user skeletons.
> [9.x] Fixes view service provider terminating callbacks

- src/Exceptions/Handler.php
The AuthorizationException handled here can have an optionally set status code. By default this status is `null`, so the previous code to map this to 403 seems correct. But if I throw a `(new AuthorizationException())->withStatus(401)` I would expect the exception handler to respect this code.
> Respect status code of AuthorizationException

- src/Application.php
> fix: create alias only for classes that do not exist.

- src/Application.php
- src/Console/Kernel.php
- tests/Console/KernelTest.php
- tests/FullApplicationTest.php
> Fixes `CommandStarting` and `CommandFinished` not working
