laravel/lumen-framework

composer.json
src/Application.php

Allow Lumen 5.1 to be installed.

---

src/Application.php

@taylorotwell - if I understand you correctly then you wanted a pull request to be againt 5.0 branch. Here it is.

Unused property

---

tests/FullApplicationTest.php

Change test domain name.

---

src/Application.php
src/Routing/Controller.php
src/helpers.php

Unused imports and wrong phpdocs

Minor fixes

---

config/database.php

Make it possible to configure the sqlite database file path via env file.

Configuration of sqlite database file

---

src/Routing/UrlGenerator.php

Pretty much just ported from [Laravel](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Routing/UrlGenerator.php#L102-L120).

Add full() and current() url methods

---

src/Application.php
tests/FullApplicationTest.php

For details, see https://github.com/laravel/lumen-framework/pull/54

Fix passing parameters to functions or controller methods with default values

---

config/app.php

Moved cipher setting below key setting, consistent with Laravel config layout.

Removed redundant Encryption Key section

---

src/Application.php

Seems to be missing much like the Hash one was in #75

Add missing Event Facade

---

src/Application.php

Docs claim you can use Cookie via the Facade, so lets make it so!

Added Cookie facade

---

config/database.php

Need to set password for services like RedisCloud

Add password environment var to redis DB config

---

src/Routing/UrlGenerator.php

These methods are useful for image/asset serving applications, as well as provide better possible compatibility between Lumen and several popular Laravel packages.

Add in asset and secureAsset methods and their dependent class methods

---

src/Routing/UrlGenerator.php

Added property forceSchema to class, replaced $this->request with $this->app->make('request') in getScheme()

Fixed getScheme() method

---

src/Application.php

We will be able to add our own HTTP Methods if is needed as below:
```
$app->addRoute('PROPFIND', '/principals', 'DavController@principals')
```

chg: addRoute method privacy from protected to public

---

src/Application.php

It's a minor thing, but a valid DOCTYPE sure makes things look more professional.

Added DOCTYPE to the Welcome page

---

src/Application.php

Set correct return type in docblocks

Return type in comment

---

src/Application.php
src/Console/Commands/ServeCommand.php
src/Console/Kernel.php
src/Http/Redirector.php
src/Http/ResponseFactory.php
src/Routing/Controller.php
src/Routing/UrlGenerator.php
src/Routing/ValidatesRequests.php
src/Testing/AssertionsTrait.php
src/helpers.php

Convert array() to square brackets

---

src/Application.php

So I noticed that one of the differences between Laravel and Lumen is that Lumen doesn't have a shutdown handler. This can result in some annoying WSOD should you have `display_errors` turned off.
I'm not sure if it was intentional or not but I figure the change is trivial so I'd send it through as a PR.
This was pretty much dropped in from the Laravel exception bootstrapper.

Register a shutdown handler to catch fatal errors and avoid WSOD.

---

src/Application.php

Ref: https://github.com/facebook/hhvm/blob/HHVM-3.8/hphp/runtime/base/runtime-error.h#L62

Adds HHVM runtime error code

---

composer.json
src/Exceptions/Handler.php

This syncs the dependency version constraints with those found in laravel/framework and fixes the exception handler after it was broken by changes made to symfony 2 days ago.

[5.2] Fixed broken master branch

---

src/Application.php
src/Console/Kernel.php

I did this for laravel a few weeks back. Time for lumen now.

[5.1] Proper PHP 7 throwable support

---

src/Application.php
tests/FullApplicationTest.php

Fixed bug occuring when changing order of routes

---

src/Exceptions/Handler.php

Exception Handler Fixes

---

src/Application.php

[5.2] Made Application::getPathInfo() protected

---

src/helpers.php

Instead of mixed `app()` and `Container::getInstance()->make()`.

`Laravel\Lumen\Http\ResponseFactory` doesn't take any argument on construct, and standardise app() usage

---

src/Application.php
src/Http/Middleware/VerifyCsrfToken.php

Clean-up multiple docblock and avoid redundant call to $this->app when under Laravel\Lumen\Application.

---

src/Foundation/Testing/WithoutMiddleware.php

Added WithoutMiddleware trait for easier testing.

Added WithoutMiddleware Trait

---

src/Application.php
tests/FullApplicationTest.php

The App::environment() method is not implemented correctly per the documentation page: http://lumen.laravel.com/docs/installation#custom-configuration-files

Fixed environment and isDownForMaintenance methods

---

composer.json

[5.1] Bumped min random_compat version

---

src/Application.php

[5.1] Fix welcome page alignment

---

tests/Http/ResponseFactoryTest.php

is it writing some unit tests useful?

added basic unit tests for ResponseFactory

---

src/Application.php

`$this->path().'/resources/lang'` points to `/app/resources/lang`, but should point to `/resources/lang`.

Fix app language path

---

src/Concerns/RoutesRequests.php

Reverts laravel/lumen-framework#347

Revert "Do not recreate dispatcher on every dispatch()"

---

config/auth.php

See https://github.com/laravel/lumen/pull/58

'API' isn't a supported driver

---

src/Application.php
tests/FullApplicationTest.php

[5.2] Allow resolving the validation factory by contract

---

composer.json

Looks like the view dependency got lost along the way.

[5.3] Fixed bad composer merge

---

src/helpers.php

This is needed to get the new pagination package working.

[5.3] Added resource path helper

---

src/Concerns/RoutesRequests.php
tests/FullApplicationTest.php

Matches the functionality https://github.com/laravel/framework/pull/14059

[5.3] Support invokable actions (ADR support)

---

src/helpers.php

please help to add missing helper function trans

[5.3] Missing trans function

---

src/Application.php

Fix accessing wrong authenticated user in request

---

src/helpers.php

[5.3] Add support to the secure param on the route helper

---

src/helpers.php

Same as https://github.com/laravel/lumen-framework/pull/551/files but for the 5.3 branch.

[5.3] Update event docblock

---

src/helpers.php

Trans helper function updated after Symfony's translator

[5.4] Trans helper function update

---

src/Routing/Pipeline.php

fix issues 553

---

composer.json

Like added in https://github.com/laravel/framework/pull/17002/commits/ee8d26cc92db06f01213ac7c1b504610777a4946

[5.4] Suggests tinker package

---

src/Concerns/RoutesRequests.php

[5.4] Fit trailing slash, Same as Laravel

---

src/helpers.php

Added missing `trans_choice` function supported by laravel 5.4

trans_choice function

---

src/Testing/DatabaseTransactions.php

Add support connectionsToTransact attribute
#640

Support connectionsToTransact feature in Lumen

---

src/Routing/ProvidesConvenienceMethods.php
tests/FullApplicationTest.php

I was hoping to make use of it in Lumen as well, but realized it wasn't implemented. So this is my attempt to use the same feature here.

Implementation of Laravel 5.5 feature: Request Data From Validation

---

tests/FullApplicationTest.php
tests/Http/ResponseFactoryTest.php

I've refactored some tests with [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse) and [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue) methods.

Use assertFalse and assertTrue

---

src/helpers.php

this PR Adds the **validator()** helper function

validator helper function

---

src/Routing/UrlGenerator.php

* Opt for unified `URL::formatScheme()` over Lumen's `URL::getScheme()`.
* Opt for unified `URL::forceScheme()` over Lumen's `URL::forceSchema()`
* Add option to `forceRootUrl()` as available in Laravel.

[5.5] Improve compatibility between Laravel and Lumen UrlGenerator.

---

src/Testing/DatabaseTransactions.php

[5.5] Fix "Too Many Connections" error during testing

---

src/Routing/ProvidesConvenienceMethods.php

Added `@throws ValidationException`

---

src/Concerns/RoutesRequests.php
src/Http/Request.php
tests/FullApplicationTest.php

This pull request aims to fix an incompatibility between Laravel and Lumen's route resolvers. Since Lumen uses a different router, namely "fast-route", there is a difference between the two route resolvers. The difference causes an `Call to a member function parameter() on array` exception while trying to call the `route` method with a parameter in Illuminate's Request class.
The `route` method, when a parameter has been passed, can be used to extract the GET value of the current route. It will try to do so by calling the `parameter` method on the route resolver. This works fine within Laravel, because the route resolver returns an object. Within Lumen, however, the route resolver will return an array. Hence the exception.
In order to fix this issue, i created a custom Request class …

[5.7] Extension of Illuminate's Request class within Lumen, in order to fix an incompatibility between Laravel and Lumen.

---

src/helpers.php

This updates the annotation to match the signature of the Laravel framework helper. Fixes #716

[5.7] Update return annotation for trans helper

---

config/logging.php
config/queue.php

Changes in Laravel 5.7 configuration.
Also needs to update to [laravel/lumen][repo].
[repo]: https://github.com/laravel/lumen

[5.7] Add Laravel 5.7 changes

---

config/app.php
config/broadcasting.php
config/cache.php
config/database.php
config/logging.php
config/queue.php
config/services.php
config/view.php

Update configs to make them more similar to Laravel's.

[5.7] Update config files. Add services.php

---

src/Http/Request.php

This pull request makes the "offsetExists" and "routeIs" method in the `Illuminate\Http\Request` class compatible with Lumen.

[5.7] Make the "offsetExists" and "routeIs" method compatible with Lumen.

---

src/Http/ResponseFactory.php

This allows creating `macros` on `response()`

Make ResponseFactory Macroable

---

src/helpers.php

See https://github.com/laravel/scout/pull/322 for context
See https://github.com/illuminate/contracts/blob/master/Container/Container.php#L134 for `Container::make` implementation

Added parameter support for app helper

---

src/Routing/UrlGenerator.php

[5.8] Use similar method as Laravel UrlGenerator::formatParameters().

---

.gitignore
composer.json
src/Testing/TestCase.php
tests/FullApplicationTest.php

Added the return types and also cleaned up the gitignore file.

[5.8] Support PHPUnit 8

---

src/helpers.php

Laravel actually has the env helper in the **support** package, so it's odd lumen would even give another implementation. I propose we move the helper to foundation in laravel/framework (because of it's dependencies) https://github.com/laravel/framework/pull/27558, and then mimic the correct implementation in lumen.

[5.8] Fixed implementation of env helper

---

src/Application.php

Return from version function was 5.8.0, update it to 5.8.2

Update version() to 5.8.2

---

config/cache.php
config/logging.php

Removed double spaces to fit the current CS.

[5.8] config space fixes

---

src/Application.php

Update version to 5.8.5 in "Application" file

Update version to 5.8.5

---

src/Application.php

Make storage path customizable
It's help to deploy Lumen application to sever-less solution like AWS Lambda
Please provide your feedbacks and if it's wrong implementation please make customizable storage

[5.8] Add custom storage path support

---

src/Bootstrap/LoadEnvironmentVariables.php

Goes with https://github.com/laravel/framework/pull/28908.

[5.9] Use the factory from the Env class

---

src/Application.php

lumen does not have ability with this, so let add deafult value as `false`
same here https://github.com/laravel/lumen-framework/pull/792
lumen does not support caching

[5.8] Add the eventsAreCached method.

---

src/helpers.php

I can't report an exception via helper method in lumen, so add the method

[5.8] Add report function helper

---

src/Testing/Concerns/MakesHttpRequests.php

Adds a function for testing requests with the OPTION HTTP method.

[5.8] Add function for testing OPTION requests

---

src/Testing/Concerns/MakesHttpRequests.php

This PR contains:
- Function for testing HTTP HEAD requests
- Function for checking whether a response doesn't contain certain JSON

[5.8] Http test functions

---

src/Exceptions/Handler.php

When a JSON response is expected, return an instance of JsonResponse in the Exception Handler. This matches the behavior of Laravel.

[6.0] Match Laravels Exception Handler when JSON is expected

---

src/Testing/Concerns/MakesHttpRequests.php

See https://github.com/laravel/framework/pull/29828

[6.x] Fix incorrect HTTP OPTION verb

---

src/helpers.php

Replaced deprecated getFromJson method with get

[6.x] Replaced deprecated getFromJson with get

---

src/Application.php

Based on laravel/framework#29790

[7.x] Remove optional methods used in service providers

---

src/Application.php

To allow use `app()->configPath()`, just like in laravel component

[6.x] Add configPath

---

config/cache.php

Reverts laravel/lumen-framework#978

Revert "[6.x] Use redis cache connection by default"

---

composer.json
src/Bootstrap/LoadEnvironmentVariables.php

Pairs with https://github.com/laravel/framework/pull/30724.

[7.x] Upgrade to phpdotenv v4

---

src/Application.php
src/Concerns/RegistersExceptionHandlers.php
src/Console/Kernel.php
src/Http/Redirector.php
src/Http/ResponseFactory.php
src/Routing/Router.php
src/Routing/UrlGenerator.php
src/Testing/Concerns/MakesHttpRequests.php
src/Testing/TestCase.php
src/helpers.php

This PR fixes spacing in docblocks.

[6.x] Fix docblock spacing

---

src/Exceptions/Handler.php

Just a tiny change to help IDEs.

[6.x] Use logger interface class constant

---

src/Application.php

This allows opcache to perform constant folding. A less drastic speedup than the change I made to laravel/framework, but still decent to have, whenever someone has a lot up service providers calling runningInConsole.

[6.x] Speedup runningInConsole

---

src/Bootstrap/LoadEnvironmentVariables.php

[6.x] Fix a typo in docblock 

---

src/Application.php

[6.x] Update version

---

composer.json
src/Testing/Concerns/MakesHttpRequests.php

[7.x] Use Illuminate\Testing\TestResponse

---

src/Testing/Concerns/MakesHttpRequests.php

[7.x] Fix invalid Illuminate\Testing\Assert import

---

composer.json

Pairs with https://github.com/laravel/framework/pull/31564.

[7.x] Added missing symfony/mime dependency

---

src/Exceptions/Handler.php

[7.x] Fixed exception rendering in debug mode

---

src/Testing/Concerns/MakesHttpRequests.php
tests/Testing/Concerns/MakesHttpRequestsTest.php

Fixed receive json, with tests.
Fixes #1060
Closes #1059

[7.x] Fixed receive json

---

.github/workflows/tests.yml

Matches exactly the command in https://github.com/laravel/framework/pull/32332.

[6.x] Updated composer install command

---

src/helpers.php

Adds request helper. I think this will be useful and will increase consistency with laravel.

[7.x] Add request helper

---

src/Concerns/RegistersExceptionHandlers.php

[7.x] Fixed call to FatalError constructor

---

src/Application.php

foreach performs 33% faster than array_walk
https://medium.com/@steveclifton_12558/array-walk-performance-test-b8cfb11511a8

[7.x] Replaced array_walk with foreach

---

composer.json

Bumped phpdotenv to v5

---

src/Application.php

Fixes an issue where AuthManager couldn't be resolved from the container.
Fixes #1089

[7.x] Fix AuthManager resolving

---

src/Application.php

Method doesn't return anything.

Fix return type in PHPDoc

---

src/Exceptions/Handler.php

Fix exception handler to report general exceptions that cannot be converted to a string automatically.

[7.x] Update Handler.php

---

src/Testing/Concerns/MakesHttpRequests.php

Fix type for response property

[8.x] Fix DocBlock for $response

---

config/database.php

[8.x] Update cache config to match Laravel

---

.github/workflows/tests.yml
composer.json

[8.x] Bump Symfony dependency

---

.styleci.yml

Just like on `laravel/framework`.

Set PHP version to 8.1 in StyleCI config

---

.github/workflows/tests.yml
composer.json

[10.x] Drop PHP 8.0

---

src/Console/ConsoleServiceProvider.php

Merging two previously approoved PR from 8.x into 9.x

[9.x] Merge 8.x into 9.x

---

src/Routing/ProvidesConvenienceMethods.php

Reverts laravel/lumen-framework#1248

Revert "Change controller validate helper method to behave like Laravel (#1247)"

---

.github/workflows/tests.yml
tests/HandleExceptionsTest.php

[9.x] Test on PHP 8.2

---

.github/workflows/tests.yml
.gitignore
composer.json
phpunit.xml.dist
tests/Http/ResponseFactoryTest.php

Allow PHPUnit v10
